spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: product-service
        uri:
          lb://PRODUCT-SERVICE
        predicates:
        - Path=/products/**,/product-category/**
        
      - id: profile-service
        uri:
          lb://PROFILE-SERVICE
        predicates:
        - Path=/auth/**,/test/**

       


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost